/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.AccountStatus;
import tech.triviumcapital.clients.java.model.AccountType;
import tech.triviumcapital.clients.java.model.DepositInstructions;
import tech.triviumcapital.clients.java.model.EarningsToDate;
import tech.triviumcapital.clients.java.model.LocalTransfer;
import tech.triviumcapital.clients.java.model.ProviderDetails;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Account
 */
class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'provider'
     */
    @Test
    void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'earningsToDate'
     */
    @Test
    void earningsToDateTest() {
        // TODO: test earningsToDate
    }

    /**
     * Test the property 'localDepositInstructions'
     */
    @Test
    void localDepositInstructionsTest() {
        // TODO: test localDepositInstructions
    }

    /**
     * Test the property 'depositInstructions'
     */
    @Test
    void depositInstructionsTest() {
        // TODO: test depositInstructions
    }

}
