/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Balance
 */
class BalanceTest {
    private final Balance model = new Balance();

    /**
     * Model tests for Balance
     */
    @Test
    void testBalance() {
        // TODO: test Balance
    }

    /**
     * Test the property 'totalBalance'
     */
    @Test
    void totalBalanceTest() {
        // TODO: test totalBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    void availableBalanceTest() {
        // TODO: test availableBalance
    }

}
