/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import tech.triviumcapital.clients.java.model.OnboardingDocumentType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOnboardingDocumentRequest
 */
class CreateOnboardingDocumentRequestTest {
    private final CreateOnboardingDocumentRequest model = new CreateOnboardingDocumentRequest();

    /**
     * Model tests for CreateOnboardingDocumentRequest
     */
    @Test
    void testCreateOnboardingDocumentRequest() {
        // TODO: test CreateOnboardingDocumentRequest
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'documentName'
     */
    @Test
    void documentNameTest() {
        // TODO: test documentName
    }

}
