/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import tech.triviumcapital.clients.java.model.Transfer;
import tech.triviumcapital.clients.java.model.TransferDetails;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DepositRequest
 */
class DepositRequestTest {
    private final DepositRequest model = new DepositRequest();

    /**
     * Model tests for DepositRequest
     */
    @Test
    void testDepositRequest() {
        // TODO: test DepositRequest
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'transferDetails'
     */
    @Test
    void transferDetailsTest() {
        // TODO: test transferDetails
    }

    /**
     * Test the property 'transfer'
     */
    @Test
    void transferTest() {
        // TODO: test transfer
    }

}
