/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.DepositInstructions;
import tech.triviumcapital.clients.java.model.LockedFixedDeposit;
import tech.triviumcapital.clients.java.model.PendingFixedDeposit;
import tech.triviumcapital.clients.java.model.ProcessingFixedDeposit;
import tech.triviumcapital.clients.java.model.ProviderDetails;
import tech.triviumcapital.clients.java.model.RedeemedFixedDeposit;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FixedDepositPlacement
 */
class FixedDepositPlacementTest {
}
