/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IndividualDetails
 */
class IndividualDetailsTest {
    private final IndividualDetails model = new IndividualDetails();

    /**
     * Model tests for IndividualDetails
     */
    @Test
    void testIndividualDetails() {
        // TODO: test IndividualDetails
    }

    /**
     * Test the property 'identityNumber'
     */
    @Test
    void identityNumberTest() {
        // TODO: test identityNumber
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
