/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.DepositInstructions;
import tech.triviumcapital.clients.java.model.ProviderDetails;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PendingFixedDeposit
 */
class PendingFixedDepositTest {
    private final PendingFixedDeposit model = new PendingFixedDeposit();

    /**
     * Model tests for PendingFixedDeposit
     */
    @Test
    void testPendingFixedDeposit() {
        // TODO: test PendingFixedDeposit
    }

    /**
     * Test the property 'placementId'
     */
    @Test
    void placementIdTest() {
        // TODO: test placementId
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'providerDetails'
     */
    @Test
    void providerDetailsTest() {
        // TODO: test providerDetails
    }

    /**
     * Test the property 'term'
     */
    @Test
    void termTest() {
        // TODO: test term
    }

    /**
     * Test the property 'depositInstructions'
     */
    @Test
    void depositInstructionsTest() {
        // TODO: test depositInstructions
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
