/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RedemptionInfo
 */
class RedemptionInfoTest {
    private final RedemptionInfo model = new RedemptionInfo();

    /**
     * Model tests for RedemptionInfo
     */
    @Test
    void testRedemptionInfo() {
        // TODO: test RedemptionInfo
    }

    /**
     * Test the property 'redemptionDate'
     */
    @Test
    void redemptionDateTest() {
        // TODO: test redemptionDate
    }

}
