/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.TransactionStatus;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Redemption
 */
class RedemptionTest {
    private final Redemption model = new Redemption();

    /**
     * Model tests for Redemption
     */
    @Test
    void testRedemption() {
        // TODO: test Redemption
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'receivedAt'
     */
    @Test
    void receivedAtTest() {
        // TODO: test receivedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
