/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscribeCallbackResponsePublicKey
 */
class SubscribeCallbackResponsePublicKeyTest {
    private final SubscribeCallbackResponsePublicKey model = new SubscribeCallbackResponsePublicKey();

    /**
     * Model tests for SubscribeCallbackResponsePublicKey
     */
    @Test
    void testSubscribeCallbackResponsePublicKey() {
        // TODO: test SubscribeCallbackResponsePublicKey
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
