/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Swift
 */
class SwiftTest {
    private final Swift model = new Swift();

    /**
     * Model tests for Swift
     */
    @Test
    void testSwift() {
        // TODO: test Swift
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'accountHolderName'
     */
    @Test
    void accountHolderNameTest() {
        // TODO: test accountHolderName
    }

    /**
     * Test the property 'accountHolderAddress'
     */
    @Test
    void accountHolderAddressTest() {
        // TODO: test accountHolderAddress
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    void bankAddressTest() {
        // TODO: test bankAddress
    }

    /**
     * Test the property 'swiftCode'
     */
    @Test
    void swiftCodeTest() {
        // TODO: test swiftCode
    }

    /**
     * Test the property 'reference'
     */
    @Test
    void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
