/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.api;

import tech.triviumcapital.clients.java.ApiException;
import tech.triviumcapital.clients.java.model.FixedDepositPlacement;
import tech.triviumcapital.clients.java.model.ProcessFixedDepositPlacementRequest;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FixedDepositApi
 */
@Disabled
public class FixedDepositApiTest {

    private final FixedDepositApi api = new FixedDepositApi();

    /**
     * Get fixed deposit placement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiV1FixeddepositPlacementPlacementidTest() throws ApiException {
        UUID placementId = null;
        FixedDepositPlacement response = api.getApiV1FixeddepositPlacementPlacementid(placementId);

        // TODO: test validations
    }
    /**
     * Get fixed deposit placement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiV1FixeddepositUserUseridTest() throws ApiException {
        UUID userId = null;
        List<FixedDepositPlacement> response = api.getApiV1FixeddepositUserUserid(userId);

        // TODO: test validations
    }
    /**
     * Start processing fixed deposit placement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putApiV1FixeddepositPlacementPlacementidTest() throws ApiException {
        UUID placementId = null;
        ProcessFixedDepositPlacementRequest processFixedDepositPlacementRequest = null;
        api.putApiV1FixeddepositPlacementPlacementid(placementId, processFixedDepositPlacementRequest);

        // TODO: test validations
    }
}
