/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.api;

import tech.triviumcapital.clients.java.ApiException;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.User;
import tech.triviumcapital.clients.java.model.UserDetails;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Returns user that has zero or more accounts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiV1UserUseridTest() throws ApiException {
        UUID userId = null;
        User response = api.getApiV1UserUserid(userId);

        // TODO: test validations
    }
    /**
     * Create new user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postApiV1UserTest() throws ApiException {
        UserDetails userDetails = null;
        User response = api.postApiV1User(userDetails);

        // TODO: test validations
    }
}
