/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import tech.triviumcapital.clients.java.model.DepositInstructions;
import tech.triviumcapital.clients.java.model.LockedFixedDeposit;
import tech.triviumcapital.clients.java.model.PendingFixedDeposit;
import tech.triviumcapital.clients.java.model.ProcessingFixedDeposit;
import tech.triviumcapital.clients.java.model.ProviderDetails;
import tech.triviumcapital.clients.java.model.RedeemedFixedDeposit;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = LockedFixedDeposit.class, name = "LockedFixedDeposit"),
  @JsonSubTypes.Type(value = PendingFixedDeposit.class, name = "PendingFixedDeposit"),
  @JsonSubTypes.Type(value = ProcessingFixedDeposit.class, name = "ProcessingFixedDeposit"),
  @JsonSubTypes.Type(value = RedeemedFixedDeposit.class, name = "RedeemedFixedDeposit"),
})

public interface FixedDepositPlacement  {
    public String getType();
}

