/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import tech.triviumcapital.clients.java.model.TransferDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RedemptionRequest
 */
@JsonPropertyOrder({
  RedemptionRequest.JSON_PROPERTY_QUANTITY,
  RedemptionRequest.JSON_PROPERTY_CURRENCY_CODE,
  RedemptionRequest.JSON_PROPERTY_TRANSFER_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class RedemptionRequest {
  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private BigDecimal quantity;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private String currencyCode;

  public static final String JSON_PROPERTY_TRANSFER_DETAILS = "transferDetails";
  private TransferDetails transferDetails;

  public RedemptionRequest() {
  }

  /**
   * Constructor with all args parameters
   */
  public RedemptionRequest(@JsonProperty(JSON_PROPERTY_QUANTITY) BigDecimal quantity, @JsonProperty(JSON_PROPERTY_CURRENCY_CODE) String currencyCode, @JsonProperty(JSON_PROPERTY_TRANSFER_DETAILS) TransferDetails transferDetails) {
    this.quantity = quantity;
    this.currencyCode = currencyCode;
    this.transferDetails = transferDetails;
  }

  public RedemptionRequest quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public RedemptionRequest currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * Get currencyCode
   * @return currencyCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public RedemptionRequest transferDetails(TransferDetails transferDetails) {
    
    this.transferDetails = transferDetails;
    return this;
  }

  /**
   * Get transferDetails
   * @return transferDetails
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSFER_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransferDetails getTransferDetails() {
    return transferDetails;
  }


  @JsonProperty(JSON_PROPERTY_TRANSFER_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransferDetails(TransferDetails transferDetails) {
    this.transferDetails = transferDetails;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedemptionRequest redemptionRequest = (RedemptionRequest) o;
    return Objects.equals(this.quantity, redemptionRequest.quantity) &&
        Objects.equals(this.currencyCode, redemptionRequest.currencyCode) &&
        Objects.equals(this.transferDetails, redemptionRequest.transferDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, currencyCode, transferDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedemptionRequest {\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    transferDetails: ").append(toIndentedString(transferDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RedemptionRequest instance;

    public Builder() {
      this(new RedemptionRequest());
    }

    protected Builder(RedemptionRequest instance) {
      this.instance = instance;
    }

    public RedemptionRequest.Builder quantity(BigDecimal quantity) {
      this.instance.quantity = quantity;
      return this;
    }
    public RedemptionRequest.Builder currencyCode(String currencyCode) {
      this.instance.currencyCode = currencyCode;
      return this;
    }
    public RedemptionRequest.Builder transferDetails(TransferDetails transferDetails) {
      this.instance.transferDetails = transferDetails;
      return this;
    }


    /**
    * returns a built RedemptionRequest instance.
    *
    * The builder is not reusable.
    */
    public RedemptionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RedemptionRequest.Builder builder() {
    return new RedemptionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RedemptionRequest.Builder toBuilder() {
    return new RedemptionRequest.Builder()
      .quantity(getQuantity())
      .currencyCode(getCurrencyCode())
      .transferDetails(getTransferDetails());
  }


}

