/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubscribeCallbackResponsePublicKey
 */
@JsonPropertyOrder({
  SubscribeCallbackResponsePublicKey.JSON_PROPERTY_PUBLIC_KEY,
  SubscribeCallbackResponsePublicKey.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class SubscribeCallbackResponsePublicKey implements SubscribeCallbackResponse {
  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  private String publicKey;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public SubscribeCallbackResponsePublicKey() {
  }

  /**
   * Constructor with all args parameters
   */
  public SubscribeCallbackResponsePublicKey(@JsonProperty(JSON_PROPERTY_PUBLIC_KEY) String publicKey, @JsonProperty(JSON_PROPERTY_TYPE) String type) {
    this.publicKey = publicKey;
    this.type = type;
  }

  public SubscribeCallbackResponsePublicKey publicKey(String publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

  /**
   * Get publicKey
   * @return publicKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public SubscribeCallbackResponsePublicKey type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscribeCallbackResponsePublicKey subscribeCallbackResponsePublicKey = (SubscribeCallbackResponsePublicKey) o;
    return Objects.equals(this.publicKey, subscribeCallbackResponsePublicKey.publicKey) &&
        Objects.equals(this.type, subscribeCallbackResponsePublicKey.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicKey, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscribeCallbackResponsePublicKey {\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SubscribeCallbackResponsePublicKey instance;

    public Builder() {
      this(new SubscribeCallbackResponsePublicKey());
    }

    protected Builder(SubscribeCallbackResponsePublicKey instance) {
      this.instance = instance;
    }

    public SubscribeCallbackResponsePublicKey.Builder publicKey(String publicKey) {
      this.instance.publicKey = publicKey;
      return this;
    }
    public SubscribeCallbackResponsePublicKey.Builder type(String type) {
      this.instance.type = type;
      return this;
    }


    /**
    * returns a built SubscribeCallbackResponsePublicKey instance.
    *
    * The builder is not reusable.
    */
    public SubscribeCallbackResponsePublicKey build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SubscribeCallbackResponsePublicKey.Builder builder() {
    return new SubscribeCallbackResponsePublicKey.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SubscribeCallbackResponsePublicKey.Builder toBuilder() {
    return new SubscribeCallbackResponsePublicKey.Builder()
      .publicKey(getPublicKey())
      .type(getType());
  }


}

