/*
 * trivium-cash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.triviumcapital.clients.java.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubscribeCallbackRequestWithSignature
 */
@JsonPropertyOrder({
  SubscribeCallbackRequestWithSignature.JSON_PROPERTY_CALLBACK_URL,
  SubscribeCallbackRequestWithSignature.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class SubscribeCallbackRequestWithSignature implements SubscribeCallbackRequest {
  public static final String JSON_PROPERTY_CALLBACK_URL = "callbackUrl";
  private String callbackUrl;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public SubscribeCallbackRequestWithSignature() {
  }

  /**
   * Constructor with all args parameters
   */
  public SubscribeCallbackRequestWithSignature(@JsonProperty(JSON_PROPERTY_CALLBACK_URL) String callbackUrl, @JsonProperty(JSON_PROPERTY_TYPE) String type) {
    this.callbackUrl = callbackUrl;
    this.type = type;
  }

  public SubscribeCallbackRequestWithSignature callbackUrl(String callbackUrl) {
    
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * Get callbackUrl
   * @return callbackUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public SubscribeCallbackRequestWithSignature type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscribeCallbackRequestWithSignature subscribeCallbackRequestWithSignature = (SubscribeCallbackRequestWithSignature) o;
    return Objects.equals(this.callbackUrl, subscribeCallbackRequestWithSignature.callbackUrl) &&
        Objects.equals(this.type, subscribeCallbackRequestWithSignature.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscribeCallbackRequestWithSignature {\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SubscribeCallbackRequestWithSignature instance;

    public Builder() {
      this(new SubscribeCallbackRequestWithSignature());
    }

    protected Builder(SubscribeCallbackRequestWithSignature instance) {
      this.instance = instance;
    }

    public SubscribeCallbackRequestWithSignature.Builder callbackUrl(String callbackUrl) {
      this.instance.callbackUrl = callbackUrl;
      return this;
    }
    public SubscribeCallbackRequestWithSignature.Builder type(String type) {
      this.instance.type = type;
      return this;
    }


    /**
    * returns a built SubscribeCallbackRequestWithSignature instance.
    *
    * The builder is not reusable.
    */
    public SubscribeCallbackRequestWithSignature build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SubscribeCallbackRequestWithSignature.Builder builder() {
    return new SubscribeCallbackRequestWithSignature.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SubscribeCallbackRequestWithSignature.Builder toBuilder() {
    return new SubscribeCallbackRequestWithSignature.Builder()
      .callbackUrl(getCallbackUrl())
      .type(getType());
  }


}

